#!/bin/bash

DIR="${1:-.}"

check() {
  # Check if there are any encrypted files in the directory
  matching_file=$(find $1 -name "*.enc.*" -print -quit)
  if [[ -n "$matching_file" ]]; then
    echo "Found encrypted file $matching_file in $1"
  else
    # Check if there are any encrypted files referenced in the kustomization file
    matching_file=$(grep -m 1 "\.\+/.*\.dec\..*" $1/kustomization.y*ml 2>/dev/null | sed -E 's/\s*-\s*//')
    if [[ -n "$matching_file" ]]; then
      echo "Found encrypted file $matching_file referensed in $1/kustomization.y*ml"
    else
      # Find references to other directories in the kustomization file and check them
      for d in $(grep "\.\+/" $1/kustomization.y*ml 2>/dev/null | sed -E 's/\s*-\s*//'); do
        if [ -d "$d" ]; then
          matching_file=$(check $d)
          if [[ -n "$matching_file" ]]; then
            echo $matching_file
            break
          fi
        fi
      done
    fi
  fi
}

matching_file=$(check $DIR)
if [[ -z "$matching_file" ]]; then
  echo "No encrypted files found"
  exit 1
fi

echo "$ARGOCD_APP_NAME is supported by sops cmp. $matching_file"
exit 0
