#!/bin/bash
set -eux -o pipefail

KUSTOMIZE_VERSION=$1

DL=/tmp/kustomize-${KUSTOMIZE_VERSION}.tar.gz
URL=https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz

[ -e $DL ] || curl -sLf --retry 3 -o $DL $URL
tar -C /tmp -xf $DL
mv /tmp/kustomize /usr/local/bin/kustomize-${KUSTOMIZE_VERSION}
rm $DL

chmod +x /usr/local/bin/kustomize-${KUSTOMIZE_VERSION}
